name: Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      # -------------------
      # Checkout repo
      # -------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------
      # Setup Python
      # -------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # -------------------
      # Install Backend dependencies
      # -------------------
      - name: Install Backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # -------------------
      # Code Quality Checks
      # -------------------
      - name: Lint with flake8
        run: flake8 Backend/

      - name: Type-check with mypy
        run: mypy Backend/

      - name: Format with black
        run: black --check Backend/

      - name: Import sorting with isort
        run: isort --check-only Backend/

      # -------------------
      # Build & Push Docker Images to ECR
      # -------------------
      - name: Login to Amazon ECR
        run: |
          echo ${{ secrets.ECR_LOGIN_TOKEN }} | docker login --username ${{ secrets.EC2_USERNAME }} --password-stdin ${{ secrets.EC2_HOST }}

      - name: Build and push Backend image
        run: |
          docker build -t backend:latest Backend/
          docker tag backend:latest ${{ secrets.EC2_HOST }}/backend:latest
          docker push ${{ secrets.EC2_HOST }}/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -t frontend:latest Frontend/
          docker tag frontend:latest ${{ secrets.EC2_HOST }}/frontend:latest
          docker push ${{ secrets.EC2_HOST }}/frontend:latest

      # -------------------
      # Save Artifact (optional)
      # -------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-artifact
          path: Backend/  # or Frontend if needed
