name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      python-version: 3.11
# python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for git diff + Codecov

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # -------------------
      # Code Quality Checks
      # -------------------
      - name: Lint with flake8
        run: flake8 Backend/

      - name: Type-check with mypy
        run: mypy Backend/

      - name: Format with black
        run: black --check Backend/

      - name: Import sorting with isort
        run: isort --check-only Backend/

      # -------------------
      # Security Scans
      # -------------------
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: 1

      - name: Run Scout Suite
        run: |
          pip install scoutsuite
          scout aws --report-dir scoutsuite-report || true
        continue-on-error: true

      # -------------------
      # CodeQL Analysis
      # -------------------
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # -------------------
      # Run Tests
      # -------------------
      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q --cov=Backend --cov-report=xml

      # -------------------
      # Upload Coverage
      # -------------------
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true

      # -------------------
      # Build & Push Docker Images
      # -------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Backend Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/backend:${GITHUB_SHA}"
          docker build -t backend:latest Backend/
          docker tag backend:latest $IMAGE_URI
          docker push $IMAGE_URI

      - name: Build and push Frontend Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/frontend:${GITHUB_SHA}"
          docker build -t frontend:latest Frontend/
          docker tag frontend:latest $IMAGE_URI
          docker push $IMAGE_URI

      # -------------------
      # Save Artifact (optional)
      # -------------------
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-artifact
          path: Backend/  # or Frontend/ if needed
