name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for git diff + Codecov

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------
      # Code Quality Checks
      # -------------------

      - name: Lint with flake8
        run: flake8 src/

      - name: Type-check with mypy
        run: mypy src/

      - name: Format with black
        run: black --check src/

      - name: Import sorting with isort
        run: isort --check-only src/

      # -------------------
      # Security Scans
      # -------------------

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: 1

      - name: Run Scout Suite
        run: |
          pip install scoutsuite
          scout aws --report-dir scoutsuite-report || true
        continue-on-error: true

      # -------------------
      # CodeQL Analysis
      # -------------------

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # -------------------
      # Run Tests
      # -------------------

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml

      # -------------------
      # Upload Coverage
      # -------------------

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true

      # -------------------
      # Save Artifact
      # -------------------

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-artifact
          path: src/
