name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # -------------------
      # SSH into EC2 and deploy
      # -------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Pull latest images from ECR
            docker pull ${{ secrets.EC2_HOST }}/backend:latest
            docker pull ${{ secrets.EC2_HOST }}/frontend:latest

            # Stop existing containers
            docker stop backend || true
            docker stop worker || true
            docker stop frontend || true

            # Remove old containers
            docker rm backend || true
            docker rm worker || true
            docker rm frontend || true

            # Run Backend container
            docker run -d --name backend -p 8000:8000 \
              -e POSTGRES_HOST=localhost \
              -e REDIS_HOST=localhost \
              ${{ secrets.EC2_HOST }}/backend:latest

            # Run Worker container
            docker run -d --name worker \
              -e BACKEND_HOST=localhost \
              ${{ secrets.EC2_HOST }}/backend:latest

            # Run Frontend container
            docker run -d --name frontend -p 80:80 \
              ${{ secrets.EC2_HOST }}/frontend:latest
