name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Backend and Frontend from ECR
        run: |
          echo "🚀 Deploying images from ECR..."
          # Example ECS deploy commands:
          # aws ecs update-service --cluster my-cluster --service backend-service --force-new-deployment
          # aws ecs update-service --cluster my-cluster --service frontend-service --force-new-deployment
          # Or you can use CloudFormation / Terraform for deployment
