name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # -------------------
      # Checkout (optional, if needed)
      # -------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------
      # Configure AWS credentials
      # -------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # -------------------
      # Update ECS Services with new Docker images
      # -------------------
      - name: Deploy Backend to ECS
        run: |
          BACKEND_IMAGE="${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}"
          echo "Deploying Backend image: $BACKEND_IMAGE"
          aws ecs update-service \
            --cluster my-cluster \
            --service backend-service \
            --force-new-deployment \
            --region us-east-1

      - name: Deploy Frontend to ECS
        run: |
          FRONTEND_IMAGE="${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}"
          echo "Deploying Frontend image: $FRONTEND_IMAGE"
          aws ecs update-service \
            --cluster my-cluster \
            --service frontend-service \
            --force-new-deployment \
            --region us-east-1
